name: cupcoff
description: Experience comfort with CUPCOFF and think only of your own design ...
version: 0.0.1+1
homepage: https://github.com/sayedAliSinaHussaini/cupcoff
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  lints: ^2.0.0



flutter:

  uses-material-design: true